on: [push, pull_request] #everytime somebody tries to push or sends a pullreq. this file is run. This is the CI-workflow

jobs:
  python-lint: #choose a name => not important which
    runs-on: ubuntu-latest
    name: CI workflow #whatever you want
    steps:
    - name: checkout source repo
      uses: actions/checkout@main #checks out sourcecode 

    - name: linting
      uses: programmingwithalex/pylinter@main #runs the github action pylinter -> runs flake8, mypy and isort linting automatically in our github action for us
      with: #optional flags
        python-root: '.'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: true #false #failing isort test will not fail the CI
        # skip-flake8: false
        # skip-mypy: false
        # skip-isort: false
        # mypy-ignore-dirs-files: ''
        # requirements-file: ''

    - name: commit isort changes #automatically fixes and pushes the isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'

    - name: push isort changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
